# Generated by Django 4.0.2 on 2022-03-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod_groups_members',
            name='devote_given',
            field=models.IntegerField(default=0),
        ),
    ]
