# Generated by Django 4.0.1 on 2022-01-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='usersignup',
        ),
    ]
