# Generated by Django 4.0.1 on 2022-01-17 06:36

from django.db import migrations, models
import vote.Views.Keyview


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod_key',
            name='pod_key',
            field=models.CharField(default=vote.Views.Keyview.key_generator, editable=False, max_length=6, unique=True),
        ),
    ]
