# Generated by Django 4.0.1 on 2022-01-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod_member',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
