# Generated by Django 4.0.2 on 2022-02-17 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seconddel_groups',
            name='group_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.firstdel_groups'),
        ),
        migrations.AlterField(
            model_name='seconddel_groups_members',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.firstdel_groups'),
        ),
    ]
