# Generated by Django 4.0.1 on 2022-02-07 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='eligible',
        ),
    ]
