# Generated by Django 4.0.1 on 2022-01-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='confirmation',
            field=models.CharField(max_length=200),
        ),
    ]
