# Generated by Django 4.0.2 on 2022-03-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_pod_groups_members_devote_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='fifthdel_groups_members',
            name='devote_given',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='firstdel_groups_members',
            name='devote_given',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fourthdel_groups_members',
            name='devote_given',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seconddel_groups_members',
            name='devote_given',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sixthdel_groups_members',
            name='devote_given',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thirddel_groups_members',
            name='devote_given',
            field=models.IntegerField(default=0),
        ),
    ]
