# Generated by Django 4.0.2 on 2022-02-17 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_seconddel_groups_group_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seconddel_groups_members',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
