# Generated by Django 4.0.1 on 2022-01-17 06:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_pod_key_pod_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod_key',
            name='pod_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
