# Generated by Django 4.0.1 on 2022-02-07 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_remove_user_eligible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstdel_groups_members',
            name='elect_count',
        ),
    ]
