# Generated by Django 4.0.1 on 2022-01-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_pod_member_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod_member',
            name='verify_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
