# Generated by Django 4.0.1 on 2022-01-13 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_usersignup_confirmation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usersignup',
            new_name='user',
        ),
    ]
