# Generated by Django 4.0.1 on 2022-02-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_remove_firstdel_groups_members_elect_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstdel_groups_members',
            name='elect_count',
            field=models.IntegerField(default=0),
        ),
    ]
