# Generated by Django 4.0.1 on 2022-01-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_alter_pod_key_pod_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pod_key',
            new_name='pod',
        ),
    ]
