# Generated by Django 4.0.2 on 2022-02-17 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_alter_seconddel_groups_members_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seconddel_groups_members',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.seconddel_groups'),
        ),
    ]
