# Generated by Django 4.0.3 on 2022-03-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_alter_user_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirmation',
            new_name='Registration_Status',
        ),
    ]
