# Generated by Django 4.0.1 on 2022-02-07 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_firstdel_groups_members_elect_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstdel_groups_members',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.firstdel_groups'),
        ),
    ]
