# Generated by Django 4.0.1 on 2022-01-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_rename_pod_key_pod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod',
            name='pod_key',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
