# Generated by Django 4.0.2 on 2022-03-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entry_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
