# Generated by Django 4.0.1 on 2022-01-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_alter_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
