# Generated by Django 4.0.2 on 2022-02-17 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_alter_seconddel_groups_group_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirddel_groups_members',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.thirddel_groups'),
        ),
    ]
