# Generated by Django 4.0.3 on 2022-03-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_rename_confirmation_user_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
