# Generated by Django 4.0.1 on 2022-01-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_pod_created_at_pod_updated_at_pod_member_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod_member',
            name='approval_states',
            field=models.IntegerField(null=True),
        ),
    ]
