# Generated by Django 4.0.1 on 2022-01-17 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_alter_pod_pod_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='pod_owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
