# Generated by Django 4.0.2 on 2022-02-18 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_alter_thirddel_groups_members_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourthdel_groups_members',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.fourthdel_groups'),
        ),
    ]
