# Generated by Django 3.2.8 on 2022-01-27 14:47

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_pod_created_at_pod_updated_at_pod_member_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod_member',
            name='verify_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
