# Generated by Django 4.0.1 on 2022-01-18 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_pod_pod_owner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='pod_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.pod')),
            ],
        ),
    ]
