# Generated by Django 4.0.1 on 2022-01-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
