# Generated by Django 4.0.1 on 2022-01-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_pod_member_approval_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod_member',
            name='text_states',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
