# Generated by Django 4.0.2 on 2022-02-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_alter_fifthdel_groups_members_group_and_more'),
        ('vote', '0007_alter_fourthdel_groups_members_group'),
    ]

    operations = [
    ]
