# Generated by Django 4.0.2 on 2022-02-18 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_merge_20220218_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sixthdel_groups_members',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.sixthdel_groups'),
        ),
    ]
