# Generated by Django 4.0.1 on 2022-01-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_alter_pod_member_verify_id'),
        ('vote', '0008_pod_member_text_states'),
    ]

    operations = [
    ]
