# Generated by Django 4.0.1 on 2022-01-29 13:40

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_merge_20220129_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod_member',
            name='verify_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
