# Generated by Django 4.0.1 on 2022-01-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_alter_pod_member_verify_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pod_member',
            old_name='approval_states',
            new_name='approval_status',
        ),
        migrations.RenameField(
            model_name='pod_member',
            old_name='text_states',
            new_name='text_status',
        ),
    ]
