# Generated by Django 4.0.1 on 2022-01-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0011_rename_approval_states_pod_member_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod_member',
            name='Elect_count',
            field=models.IntegerField(default=0),
        ),
    ]
