# Generated by Django 4.0.1 on 2022-02-01 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0012_pod_member_elect_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pod_member',
            name='Elect_count',
        ),
        migrations.CreateModel(
            name='elect_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Elect_count', models.IntegerField(default=0)),
                ('Elect_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
