# Generated by Django 4.0.1 on 2022-02-01 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0013_remove_pod_member_elect_count_elect_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='elect_count',
            name='Elect_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.pod_member'),
        ),
    ]
