# Generated by Django 4.0.1 on 2022-02-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0015_alter_elect_count_elect_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pod_member',
            old_name='count',
            new_name='elect_count',
        ),
        migrations.RenameField(
            model_name='pod_member',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='pod_member',
            old_name='text_status',
            new_name='member_comment',
        ),
        migrations.RenameField(
            model_name='pod_member',
            old_name='approval_status',
            new_name='member_status',
        ),
        migrations.RenameField(
            model_name='pod_member',
            old_name='pod_id',
            new_name='pod',
        ),
        migrations.AddField(
            model_name='pod_member',
            name='elect_vote_given',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pod_member',
            name='pod_vote_given',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pod_member',
            name='pod_votes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='elect_count',
        ),
    ]
