# Generated by Django 4.0.1 on 2022-02-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0017_rename_pod_owner_id_pod_pod_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod_member',
            name='pod_vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
