# Generated by Django 4.0.1 on 2022-02-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0019_remove_pod_member_pod_vote_given'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pod_member',
            old_name='pod_votes_count',
            new_name='pod_vote_given',
        ),
    ]
