# Generated by Django 4.0.1 on 2022-02-01 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0020_rename_pod_votes_count_pod_member_pod_vote_given'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pod_member',
            name='verify_id',
        ),
    ]
