# Generated by Django 4.0.1 on 2022-02-02 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0022_rename_pod_key_pod_group_key_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pod',
            new_name='pod_groups',
        ),
        migrations.RenameModel(
            old_name='pod_member',
            new_name='pod_groups_members',
        ),
    ]
