# Generated by Django 4.0.1 on 2022-02-02 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0023_rename_pod_pod_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pod_groups_members',
            old_name='pod',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='pod_groups_members',
            old_name='pod_vote_count',
            new_name='vote_count',
        ),
        migrations.RenameField(
            model_name='pod_groups_members',
            old_name='pod_vote_given',
            new_name='vote_given',
        ),
    ]
