# Generated by Django 4.0.1 on 2022-02-02 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0024_rename_pod_pod_groups_members_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pod_groups',
            old_name='group_owner_id',
            new_name='group_owner',
        ),
    ]
