# Generated by Django 4.0.1 on 2022-02-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0025_rename_group_owner_id_pod_groups_group_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Executed_on',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='eligible',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='registered',
            field=models.IntegerField(default=0),
        ),
    ]
