# Generated by Django 4.0.1 on 2022-02-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0026_user_executed_on_user_address_user_eligible_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Executed_on',
            new_name='executed_on',
        ),
    ]
